 export const environment = {
    production: true,
    allianceImg: 'assets/images/alliance.svg',
    allianceWhiteImg:'assets/images/alliance_white.svg',
    allianceSquare:'assets/images/alliance_square.svg',
    allianceText:'assets/images/alliance_text.svg',
    facebookIcon:'assets/images/socials/facebook.svg',
    instagramIcon:'assets/images/socials/insta.svg',
    linkedinIcon:'assets/images/socials/linkedin.svg',
    twitterIcon:'assets/images/socials/twitter.svg',
    youtubeIcon:'assets/images/socials/youtube.svg',
    apiURL:'http://localhost:8081/spring-hibernate-jpa',
    auth_key:'Basic Y2xpZW50OnNlY3JldA==',
    loadingTime: 2000,
  };